apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: openshift-serverless-operator
  namespace: openshift-marketplace
spec:
  displayName: OpenShift Serverless
  image: nexus.sepp.net:5000/repository/serverless/openshift-pipelines-operator-midstr-index:latest
  publisher: openshift-serverless
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 15m
